# Generated by Django 5.0.1 on 2024-06-09 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_rename_date_added_entry_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='access_permission',
            field=models.CharField(choices=[('public', 'Public'), ('authenticated', 'Authenticated'), ('vip', 'VIP')], default='public', max_length=32),
        ),
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning_logs.topic'),
        ),
    ]
