# Generated by Django 5.0.1 on 2024-06-09 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_entry_access_permission_alter_entry_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='learning_logs.topic'),
        ),
    ]
